### ISSUE TITLE
【账户绑定】移动端无法绑定 telegram。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-Mobile-FE#145]
<img width="347" alt="屏幕快照 2020-01-18 下午6 56 16" src="https://user-images.githubusercontent.com/2507027/72662636-59ea9180-3a24-11ea-8c60-c9fe83b4e1fa.png">

移动端无法绑定 telegram。

**Comment by shellteo** [comment]
微信端打开好似frontenduse.top这个域名，tgbox不能识别

**Comment by shellteo** [comment]
fixed in https://github.com/Matataki-io/Matataki-Mobile-FE/pull/159
