### ISSUE TITLE
【界面】实际已关注，但却显示未登录

### ISSUE THREAD

**Issue by billchenchina** [Matataki-io/Matataki-Mobile-FE#147]
**操作系统**：安卓
**浏览器**：Chrome浏览器
**出现环境**：Prod版本

**描述这个bug**
实际（`/user/:id/fan`）已关注某用户，但 `/user/:id` 显示并未关注。

**复现流程**
1. 登录 Matataki
2. 打开 `/user/:id`，此处的“关注”按钮可以点击，点击后提示“关注失败”并弹出登陆界面
3. 打开 `/user/:id/fan`，粉丝列表中有自己。（实际已关注）

**预期结果**
按钮显示“已关注”，而非“关注”

**问题截图**
![IMG_20200119_145600_685](https://user-images.githubusercontent.com/7758042/72676401-d84e3e80-3acb-11ea-9b17-ab14deff4ceb.jpg)

粉丝界面：![IMG_20200119_145558_193](https://user-images.githubusercontent.com/7758042/72676403-dab09880-3acb-11ea-8007-3dd51b77bce9.jpg)

**备注信息**
无

**Comment by lychees** [comment]
无法复现，
可能只是网路问题。

**Comment by billchenchina** [comment]
orz 然而我这里可以稳定复现的说= =
