### ISSUE TITLE
【文章】多余的解锁信息

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-Mobile-FE#37]
<img width="775" alt="屏幕快照 2019-12-16 下午1 11 04" src="https://user-images.githubusercontent.com/2507027/70931509-a0a03280-2005-11ea-9ada-1e83b5d31ed5.png">

移动端打开。。。
https://smartsignature.frontenduse.top/p/1062?c=3aad1601

**Comment by LittleSound** [comment]
https://github.com/Matataki-io/Matataki-Mobile-FE/pull/46

**Comment by LittleSound** [comment]
已经修复了这个问题

**Comment by lychees** [comment]
Confirmed. Thanks.
